import {expect,test,type WebSocketRoute} from '@playwright/test';
import {makeBlock,type Board} from '../../src/model';
test('streamed assistant edits respect a manual drag and undo in the actual editor',async({page})=>{
 await page.route('**/api/bootstrap',r=>r.fulfill({json:{token:'test-token',configured:true,debugProtocol:1,models:{transcription:'test',interpretation:'test'}}}));
 await page.routeWebSocket('**/api/control?*',socket=>socket.onMessage(raw=>{const m=JSON.parse(String(raw));if(m.type==='register')socket.send(JSON.stringify({type:'registered',id:'test-editor'}));}));
 let socket:WebSocketRoute|null=null;let context:{board:Board;editing:boolean;historyEpoch:number}|null=null;
 const acknowledgements:{id:string;applied:boolean}[]=[];
 await page.routeWebSocket('**/api/live?*',route=>{socket=route;route.onMessage(raw=>{
  const m=JSON.parse(String(raw));if(m.context)context=m.context;
  if(m.type==='start')route.send(JSON.stringify({type:'ready',input:'text'}));
  if(m.type==='ack')acknowledgements.push(m);
 });});
 await page.goto('/');await page.getByRole('textbox',{name:'Diagnostic test text'}).fill('There is a welcome screen');
 await page.getByRole('button',{name:'Send text test',exact:true}).click();
 await expect.poll(()=>!!socket&&!!context).toBe(true);
 const send=(id:string,baseRevision:number,operations:unknown[])=>socket!.send(JSON.stringify({type:'transaction',transaction:{id,baseRevision,source:'ai',operations},message:'Updating the sketch.',elapsedMs:100}));
 send('first',context!.board.revision,[{type:'add',block:makeBlock('step','Welcome',{x:300,y:200},{id:'welcome'})}]);
 await expect(page.locator('[data-board-object="welcome"]')).toContainText('Welcome');
 await page.getByRole('button',{name:'Close debug panel',exact:true}).click();
 await page.getByRole('button',{name:'Fit view',exact:true}).click();
 const before=context!.board;const block=before.blocks[0], stage=page.locator('.cv-native-stage');
 const zoom=Number(await stage.getAttribute('data-zoom')),x=(block.position.x+block.width/2+Number(await stage.getAttribute('data-scroll-x')))*zoom,y=(block.position.y+block.height/2+Number(await stage.getAttribute('data-scroll-y')))*zoom;
 await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+110,y+70,{steps:8});await page.mouse.up();
 await expect.poll(()=>context!.board.revision).toBeGreaterThan(before.revision);
 const moved=context!.board.blocks[0].position;
 await expect(page.locator('[data-material-card="welcome"]')).toBeVisible();
 const painted=await page.locator('[data-material-card="welcome"]').boundingBox();
 const actualZoom=Number(await stage.getAttribute('data-zoom'));
 expect(Math.abs(painted!.x-(moved.x+Number(await stage.getAttribute('data-scroll-x')))*actualZoom)).toBeLessThan(1);
 await expect(page.locator('.cv-material-layer')).toHaveCSS('pointer-events','none');
 send('stale',before.revision,[{type:'update',id:'welcome',patch:{label:'Stale label'}}]);
 await expect.poll(()=>acknowledgements.find(a=>a.id==='stale')?.applied).toBe(false);
 expect(context!.board.blocks[0].position).toEqual(moved);
 send('fresh',context!.board.revision,[{type:'update',id:'welcome',patch:{label:'Start your run'}}]);
 await expect(page.locator('[data-board-object="welcome"]')).toContainText('Start your run');
 expect(context!.board.blocks[0].position).toEqual(moved);
 const epoch=context!.historyEpoch;await page.locator('.excalidraw').press('ControlOrMeta+z');
 await expect(page.locator('[data-board-object="welcome"]')).toContainText('Welcome');
 await expect.poll(()=>context!.historyEpoch).toBeGreaterThan(epoch);
});
