import {expect,test} from '@playwright/test';
test('neobrutalist diamonds retain native bindings and remain editable inside transparent frames',async({page,request})=>{
 await page.goto('/');const connected=page.getByText(/^Connected editor:/);await expect(connected).toBeVisible();const id=(await connected.innerText()).split(': ').at(-1)!;
 const bootstrap=await(await request.get('/api/bootstrap')).json();const headers={Authorization:`Bearer ${bootstrap.token}`},endpoint=`/api/agent/boards/${id}`;
 await page.getByRole('button',{name:'Close debug panel'}).click();
 const events=[{type:'topic',id:'neo',label:'Permission flow'},{type:'view',kind:'presentation'},{type:'concept',id:'section',role:'section',label:'Invitation access'},{type:'concept',id:'start',role:'step',label:'Start'},{type:'concept',id:'validate',role:'step',label:'Validate invitation'},{type:'concept',id:'auth',role:'decision',label:'Authorized?'},{type:'concept',id:'proceed',role:'step',label:'Proceed'},{type:'concept',id:'failure',role:'note',label:'Request a new invitation',outcome:'failure'},...['start','validate','auth','proceed','failure'].map(to=>({type:'relation',from:'section',to,kind:'contains'})),{type:'relation',from:'start',to:'validate',kind:'next'},{type:'relation',from:'validate',to:'auth',kind:'next'},{type:'relation',from:'auth',to:'proceed',kind:'next',label:'yes'},{type:'relation',from:'auth',to:'failure',kind:'branch',label:'no'}];
 const response=await request.post(endpoint+'/actions',{headers,data:{requestId:'neo-reference',baseRevision:0,action:{kind:'meaning',events}}});expect(response.ok()).toBe(true);
 const diamond=page.locator('[data-material-card="neo__auth"]');await expect(diamond).toBeVisible();await page.waitForTimeout(1400);await page.evaluate(()=>document.fonts.ready);
 await expect(diamond).toHaveAttribute('data-native-shape','diamond');await expect(page.locator('.cv-material-layer .cv-block')).toHaveCount(0);
 const before=(await diamond.boundingBox())!;await page.mouse.move(before.x+before.width/2,before.y+before.height/2);await page.mouse.down();await page.mouse.move(before.x+before.width/2+36,before.y+before.height/2+12,{steps:5});await page.mouse.up();await expect(diamond).toHaveAttribute('data-selected','true');const after=(await diamond.boundingBox())!;expect(after.x-before.x).toBeGreaterThan(25);
 await expect.poll(async()=>!!(await(await request.get(endpoint,{headers})).json()).board.native).toBe(true);
 const board=(await(await request.get(endpoint,{headers})).json()).board;
 const native=board.native.elements;expect(native.find((e:any)=>e.id==='neo__auth').type).toBe('diamond');expect(native.find((e:any)=>e.id==='neo__section').backgroundColor).toBe('transparent');
 const arrows=native.filter((e:any)=>e.type==='arrow'&&e.startBinding&&e.endBinding);expect(arrows.length).toBeGreaterThanOrEqual(4);expect(arrows.every((e:any)=>e.strokeColor==='#000000'&&e.endArrowhead==='triangle'&&e.elbowed)).toBe(true);
 const shape=native.find((e:any)=>e.id==='neo__auth'),label=native.find((e:any)=>e.type==='text'&&e.containerId===shape.id);expect(shape.backgroundColor).toBe('#ff006f');expect(label.width).toBeLessThanOrEqual(shape.width*.55);expect(label.y).toBeGreaterThan(shape.y);expect(label.y+label.height).toBeLessThan(shape.y+shape.height);
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'Fit view',exact:true}).click();await page.waitForTimeout(300);await page.screenshot({path:'.impeccable/review/neo/native-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Fit view',exact:true}).click();await page.waitForTimeout(300);await page.screenshot({path:'.impeccable/review/neo/native-mobile.png',fullPage:true});
 await page.goto('/directions');await expect(page.getByRole('heading',{name:'Neobrutalism',exact:true})).toBeVisible();await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'.impeccable/review/neo/lab-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.impeccable/review/neo/lab-mobile.png',fullPage:true});
});
